jwt:
  # JWT 서명에 사용할 비밀 키. 실제 프로덕션에서는 훨씬 더 길고 복잡해야 하며, 환경 변수 등으로 관리해야 합니다.
  secret: V2VMaXZlSW5BVkNBdGl0eUFkdmFuY2VkQ29tcGFueUFjdGl2ZWx5RGV2ZWxvcGluZ01TQUZvclRoZUZ1dHVyZQo=
  # 토큰 만료 시간 (밀리초 단위). 여기서는 1시간으로 설정.
  expiration-time: 3600000